default: &default
  adapter: mysql2
  database: purecitizen
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: <%= ENV.fetch("LOGIN") %>
  password: <%= ENV.fetch("PASSWORD") %>

development:
  <<: *default

test:
  <<: *default
  database: purecitizen_test

production:
  <<: *default
